
#line 3 "lex.ChDes.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ChDes_create_buffer
#define yy_delete_buffer ChDes_delete_buffer
#define yy_scan_buffer ChDes_scan_buffer
#define yy_scan_string ChDes_scan_string
#define yy_scan_bytes ChDes_scan_bytes
#define yy_init_buffer ChDes_init_buffer
#define yy_flush_buffer ChDes_flush_buffer
#define yy_load_buffer_state ChDes_load_buffer_state
#define yy_switch_to_buffer ChDes_switch_to_buffer
#define yypush_buffer_state ChDespush_buffer_state
#define yypop_buffer_state ChDespop_buffer_state
#define yyensure_buffer_stack ChDesensure_buffer_stack
#define yy_flex_debug ChDes_flex_debug
#define yyin ChDesin
#define yyleng ChDesleng
#define yylex ChDeslex
#define yylineno ChDeslineno
#define yyout ChDesout
#define yyrestart ChDesrestart
#define yytext ChDestext
#define yywrap ChDeswrap
#define yyalloc ChDesalloc
#define yyrealloc ChDesrealloc
#define yyfree ChDesfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define ChDes_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer ChDes_create_buffer
#endif

#ifdef yy_delete_buffer
#define ChDes_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer ChDes_delete_buffer
#endif

#ifdef yy_scan_buffer
#define ChDes_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer ChDes_scan_buffer
#endif

#ifdef yy_scan_string
#define ChDes_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string ChDes_scan_string
#endif

#ifdef yy_scan_bytes
#define ChDes_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes ChDes_scan_bytes
#endif

#ifdef yy_init_buffer
#define ChDes_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer ChDes_init_buffer
#endif

#ifdef yy_flush_buffer
#define ChDes_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer ChDes_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define ChDes_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state ChDes_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define ChDes_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer ChDes_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define ChDespush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state ChDespush_buffer_state
#endif

#ifdef yypop_buffer_state
#define ChDespop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state ChDespop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define ChDesensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack ChDesensure_buffer_stack
#endif

#ifdef yylex
#define ChDeslex_ALREADY_DEFINED
#else
#define yylex ChDeslex
#endif

#ifdef yyrestart
#define ChDesrestart_ALREADY_DEFINED
#else
#define yyrestart ChDesrestart
#endif

#ifdef yylex_init
#define ChDeslex_init_ALREADY_DEFINED
#else
#define yylex_init ChDeslex_init
#endif

#ifdef yylex_init_extra
#define ChDeslex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra ChDeslex_init_extra
#endif

#ifdef yylex_destroy
#define ChDeslex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy ChDeslex_destroy
#endif

#ifdef yyget_debug
#define ChDesget_debug_ALREADY_DEFINED
#else
#define yyget_debug ChDesget_debug
#endif

#ifdef yyset_debug
#define ChDesset_debug_ALREADY_DEFINED
#else
#define yyset_debug ChDesset_debug
#endif

#ifdef yyget_extra
#define ChDesget_extra_ALREADY_DEFINED
#else
#define yyget_extra ChDesget_extra
#endif

#ifdef yyset_extra
#define ChDesset_extra_ALREADY_DEFINED
#else
#define yyset_extra ChDesset_extra
#endif

#ifdef yyget_in
#define ChDesget_in_ALREADY_DEFINED
#else
#define yyget_in ChDesget_in
#endif

#ifdef yyset_in
#define ChDesset_in_ALREADY_DEFINED
#else
#define yyset_in ChDesset_in
#endif

#ifdef yyget_out
#define ChDesget_out_ALREADY_DEFINED
#else
#define yyget_out ChDesget_out
#endif

#ifdef yyset_out
#define ChDesset_out_ALREADY_DEFINED
#else
#define yyset_out ChDesset_out
#endif

#ifdef yyget_leng
#define ChDesget_leng_ALREADY_DEFINED
#else
#define yyget_leng ChDesget_leng
#endif

#ifdef yyget_text
#define ChDesget_text_ALREADY_DEFINED
#else
#define yyget_text ChDesget_text
#endif

#ifdef yyget_lineno
#define ChDesget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno ChDesget_lineno
#endif

#ifdef yyset_lineno
#define ChDesset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno ChDesset_lineno
#endif

#ifdef yywrap
#define ChDeswrap_ALREADY_DEFINED
#else
#define yywrap ChDeswrap
#endif

#ifdef yyalloc
#define ChDesalloc_ALREADY_DEFINED
#else
#define yyalloc ChDesalloc
#endif

#ifdef yyrealloc
#define ChDesrealloc_ALREADY_DEFINED
#else
#define yyrealloc ChDesrealloc
#endif

#ifdef yyfree
#define ChDesfree_ALREADY_DEFINED
#else
#define yyfree ChDesfree
#endif

#ifdef yytext
#define ChDestext_ALREADY_DEFINED
#else
#define yytext ChDestext
#endif

#ifdef yyleng
#define ChDesleng_ALREADY_DEFINED
#else
#define yyleng ChDesleng
#endif

#ifdef yyin
#define ChDesin_ALREADY_DEFINED
#else
#define yyin ChDesin
#endif

#ifdef yyout
#define ChDesout_ALREADY_DEFINED
#else
#define yyout ChDesout
#endif

#ifdef yy_flex_debug
#define ChDes_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug ChDes_flex_debug
#endif

#ifdef yylineno
#define ChDeslineno_ALREADY_DEFINED
#else
#define yylineno ChDeslineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[123] =
    {   0,
       36,   34,   35,   35,   34,   35,   34,   35,    9,   35,
       34,   35,   34,   35,   34,   35,   34,   35,16406,   34,
       35,   34,   35,   34,   35,   34,   35,   34,   35,   34,
       35,   34,   35,   34,   35,   34,   35,   34,   35,   34,
       35,   34,   35,   34,   35,   34,   35,   34,   35,   34,
       35,    9,16406,   33,   15,   26,   28,   30,    7,    9,
       19,   20,   32,   24,16411,16413,16409, 8214,   31,   18,
     8219,   23, 8221, 8217,    4,    9,    8,    9,16405,   16,
       19, 8213,    5,    9,    6,    9,   17,   19,    9,   19,
       14,   19,16397,16397,    2,    5,    9,    2,    6,    9,

     8205,   19, 8205,   12,   19,   12,    1,    5,    9,16394,
        1,    6,    9,16394, 8202,   12,   19,    3, 8202,   12,
       11,   19
    } ;

static const flex_int16_t yy_accept[410] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    7,    9,   11,   13,   15,   17,
       20,   22,   24,   26,   28,   30,   32,   34,   36,   38,
       40,   42,   44,   46,   48,   50,   52,   52,   53,   53,
       53,   53,   53,   53,   53,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       55,   55,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   57,   57,   58,   58,
       59,   59,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   62,   62,   62,   63,   63,   63,   64,   65,
       66,   67,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   70,   71,   72,   72,   72,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       74,   75,   75,   75,   77,   77,   79,   79,   79,   79,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   82,   82,   82,   82,   82,   82,

       82,   82,   82,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   87,   87,   87,   87,   87,   87,   87,   87,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   89,   89,   89,   89,   89,   89,   89,   90,   90,

       90,   91,   91,   91,   91,   91,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   94,   95,
       95,   95,   95,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,  101,  101,  101,  101,  101,  101,  101,
      101,  103,  104,  104,  104,  104,  104,  104,  106,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  110,
      110,  110,  111,  111,  114,  114,  115,  115,  115,  115,

      115,  118,  118,  119,  121,  121,  121,  123,  123
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,    7,    8,    9,
        9,    9,    9,    9,    9,    9,   10,   11,    1,   12,
        1,   13,    1,    1,   14,    1,   15,    1,   16,    1,
       17,    1,    1,    1,    1,    1,   18,   19,    1,   20,
        1,    1,    1,   21,    1,    1,    1,   22,    1,    1,
        1,    1,    1,    1,    1,    1,   23,   24,   25,   26,

       27,    1,   28,    1,   29,    1,    1,   30,   31,   32,
       33,   34,    1,   35,   36,   37,   38,    1,    1,    1,
       39,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[40] =
    {   0,
        1,    2,    3,    4,    1,    1,    4,    4,    4,    4,
        5,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[459] =
    {   0,
      848,  847,  846,    0,  845,   31,  844,  843,  842,  841,
        1,    3,  840,   63,  839,  838,  837,  836,  835,  834,
      836,  852,  852,  832,    4,  852,   14,    5,   11,   94,
       17,   18,   20,  801,  795,  829,  828,    0,   41,  819,
      818,  817,  794,  823,  822,  821,  820,  852,   21,   43,
       45,   34,   28,   22,  817,   49,   56,   61,    0,  802,
      793,  816,    7,   56,  815,   78,  785,  787,  812,    0,
      811,  852,  810,  103,  801,  800,  799,  798,  804,  796,
      802,  794,  800,  771,  799,  852,  798,  852,  797,  852,
       58,  852,   73,   69,   71,   79,  795,   72,  795,  783,

      768,  852,   87,   91,  852,    0,    0,  852,  852,    0,
      783,  782,    0,   94,  108,  106,  110,  112,  776,  113,
      852,    0,  762,  114,  117,  788,  787,  786,    0,    0,
      785,  119,  122,  127,  784,  128,  767,  125,  774,  757,
      130,  141,  852,  852,  852,  780,  779,  852,  131,  145,
      134,  778,  138,  762,  147,  775,  774,  150,  136,  852,
      852,  151,  153,  852,  159,  852,  155,  773,  161,  764,
      750,  771,  163,  164,  167,  170,  166,  172,  750,  173,
        0,  739,  768,  176,  177,  179,  180,  183,  178,  738,
      184,  766,  730,  852,  186,  187,  182,  193,  197,  195,

      744,  199,  852,  732,  198,  208,  210,  205,  218,  211,
      735,  214,  737,  215,  216,  220,  221,  760,  222,  223,
      231,  723,  229,    0,  232,  240,  224,  758,  236,  237,
      852,  241,  243,  242,  724,  246,  756,  263,  247,  249,
      852,  251,  254,  259,  261,  268,  731,  272,  852,  265,
      277,  280,  279,  284,  282,  283,  286,  753,  287,  288,
      289,  285,  298,  290,  299,  295,  297,  722,  303,  293,
      304,  306,  301,  307,  327,  332,  752,  731,  309,  329,
      750,  335,  338,  339,  342,  324,  749,  716,  347,  343,
      739,  746,  349,  350,  352,  353,  356,  746,  743,  358,

      735,  359,  360,  734,  740,  852,  363,  364,  362,  740,
      365,  737,  730,  362,  373,  736,  369,  736,    0,  371,
      735,  375,  852,  376,  728,  370,  722,    0,  379,  712,
      702,  388,  852,  381,  391,  631,  384,  648,  633,  397,
      852,  852,  395,  398,  399,  604,  392,  852,  852,  411,
      408,  410,  412,  594,  405,  414,  415,  424,  420,  587,
      409,  425,  426,  427,  442,  585,  421,  443,  430,  449,
      446,  603,  432,  461,  452,  459,  465,  575,  463,  467,
      456,  468,  594,  535,  536,  476,  458,  539,  852,  513,
      486,  486,  478,  852,    0,    0,  485,  472,  474,  431,

      852,  483,  852,  852,  312,   49,  852,  852,  491,  496,
      501,  506,  511,  516,  521,  526,  531,  535,  539,  544,
      549,  554,  559,  564,  569,  574,  579,  584,  589,  594,
      599,  604,  609,  614,  619,  624,  628,  633,  638,  643,
      648,  653,  658,  663,  668,  673,  678,  683,  688,  693,
      697,  702,  707,  712,  717,  722,  727,  732
    } ;

static const flex_int16_t yy_def[459] =
    {   0,
      409,  409,  409,  410,  409,  409,  409,  411,  412,  412,
      409,  409,  409,  409,  413,  413,  414,  414,  415,  415,
      408,  408,  408,  416,  416,  408,  417,  416,  416,  408,
      418,  419,  420,  408,  408,  421,  422,  423,  408,  424,
      425,  426,  408,  427,  428,  429,  416,  408,  416,  417,
      417,  416,  416,  416,   30,  418,  419,  420,  430,  408,
      408,  419,  419,  419,  420,  420,  408,  408,  421,  431,
      422,  408,  423,  408,  424,  425,  426,  424,  408,  425,
      408,  426,  408,  408,  427,  408,  428,  408,  429,  408,
      416,  408,  417,  416,  416,  416,  408,  419,  430,  408,

      408,  408,  419,  419,  408,  432,  433,  408,  408,  434,
      408,  408,  435,  416,  417,  416,  416,  416,  408,  419,
      408,  436,  408,  419,  419,  432,  433,  434,  437,  438,
      435,  416,  417,  416,  439,  416,  408,  419,  436,  408,
      419,  419,  408,  408,  408,  437,  438,  408,  416,  417,
      416,  439,  416,  408,  419,  408,  408,  419,  419,  408,
      408,  416,  417,  408,  416,  408,  416,  408,  419,  408,
      408,  440,  419,  419,  419,  416,  416,  416,  408,  419,
      441,  408,  440,  419,  419,  419,  416,  416,  416,  408,
      419,  441,  408,  408,  419,  419,  419,  416,  416,  416,

      408,  419,  408,  408,  419,  419,  419,  416,  442,  416,
      408,  419,  408,  419,  419,  419,  443,  442,  442,  442,
      416,  408,  419,  444,  419,  419,  419,  443,  443,  443,
      408,  442,  442,  416,  408,  419,  444,  419,  419,  419,
      408,  443,  443,  442,  442,  416,  408,  419,  408,  419,
      419,  419,  443,  443,  442,  442,  416,  408,  419,  419,
      419,  419,  443,  443,  442,  442,  416,  408,  419,  419,
      419,  419,  443,  443,  442,  442,  445,  408,  419,  446,
      447,  419,  443,  443,  442,  442,  445,  408,  448,  446,
      449,  447,  419,  443,  443,  442,  442,  408,  450,  448,

      450,  448,  419,  449,  408,  408,  419,  443,  443,  442,
      442,  408,  450,  450,  419,  408,  448,  451,  452,  419,
      443,  443,  408,  442,  408,  450,  453,  454,  448,  451,
      452,  419,  408,  443,  442,  408,  450,  453,  454,  448,
      408,  408,  419,  443,  442,  408,  450,  408,  408,  448,
      419,  443,  442,  408,  450,  448,  419,  443,  442,  408,
      450,  448,  419,  443,  442,  408,  450,  448,  419,  443,
      442,  408,  450,  448,  419,  443,  442,  408,  450,  448,
      419,  443,  442,  408,  450,  419,  419,  443,  408,  408,
      408,  455,  419,  408,  456,  457,  455,  419,  456,  457,

      408,  419,  408,  408,  458,  458,  408,    0,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408
    } ;

static const flex_int16_t yy_nxt[892] =
    {   0,
      408,   25,   26,   23,   27,   23,   48,   48,   49,  102,
       52,   28,   38,   48,   38,   51,   48,   47,   56,   63,
       56,   64,   91,   48,   48,   53,   66,   66,   66,   66,
       48,   29,   30,   23,   31,   32,   48,   33,   33,   33,
       33,  103,   74,   54,   74,   92,   47,   92,   47,   95,
       56,  407,   56,   96,   94,   75,   76,   63,  102,   98,
       48,   77,   34,   35,   39,   23,   39,   66,   66,   66,
       66,   48,  104,   48,  102,   92,   47,   40,   41,   93,
      105,   48,  118,   42,   66,   66,   66,   66,  120,  102,
      116,  117,  114,  102,   43,   55,   48,   56,   57,  115,

       58,   58,   58,   58,   74,   59,   74,   60,   48,  125,
       92,   47,   48,  124,   48,  102,  102,   75,   76,  102,
      132,   48,  135,   77,   92,   47,  134,  102,   61,   48,
       48,  138,  102,   48,  142,  133,  164,  136,  102,  151,
       48,  141,  155,  102,  159,  165,  149,   92,   47,  102,
      169,  150,  102,   48,  153,   92,  177,   48,  173,  158,
      162,   48,  167,  102,   52,  102,  102,  174,   48,  102,
      175,  163,   48,  187,   48,  102,  172,  176,  102,  102,
       48,  102,   48,  180,  102,   48,  102,  178,  102,  102,
      206,  188,  174,  186,  184,   48,  185,   48,  195,   48,

      102,  102,  189,  197,  191,  198,  202,   48,  196,  199,
      102,  200,  102,   48,  207,  205,  102,  102,  102,  208,
       48,  209,  102,   48,  231,  231,  102,  210,  212,  217,
      215,  102,  219,   48,  102,  229,  214,  220,  241,  241,
      230,  216,  102,  231,   48,  231,  221,  226,  102,  102,
      225,  102,  223,  241,  232,  227,  241,  233,  238,  234,
      240,  231,  239,  231,  236,  102,  250,  102,  242,  245,
       48,  243,  248,  244,  102,  259,  251,  252,  246,  102,
      254,  241,  102,  253,  231,  231,  241,  102,   48,  102,
      102,  102,  241,  255,  256,  102,  257,  231,  260,   48,

      241,  231,  275,  241,  283,  102,  102,  265,  102,  241,
      270,  102,  266,  263,  102,  261,  262,  264,  267,  274,
      269,  276,  272,  273,  271,  279,  231,  280,  277,  231,
      281,  291,  282,  284,  231,  286,  285,  102,  293,   62,
      241,  241,  295,  289,  231,  291,  297,  294,  296,  301,
      302,  102,  241,  303,  241,  231,  308,   62,  231,  310,
      301,  301,  102,  318,  241,  102,  241,  231,  315,  315,
      321,  301,  316,  102,  309,  102,  327,  241,  231,  315,
      316,  301,  307,  241,  317,  320,  311,  326,  324,  315,
      102,  343,  322,  231,  316,  329,  337,  102,  334,  301,

      241,  231,  316,  340,  335,  332,  355,  315,  347,  344,
      102,  350,  241,  301,  231,  316,  301,  102,  345,  316,
      351,  315,  231,  365,  315,  352,  241,  301,  102,  241,
      370,  316,  102,  404,  357,  315,  353,  361,  359,  363,
      369,  367,  316,  356,  231,  301,  362,  358,  231,  371,
      364,  241,  377,  315,  102,  373,  376,  379,  102,  368,
      102,  241,  375,  301,  380,  382,  385,  231,  374,  301,
      241,  315,  383,  316,  102,  388,  403,  386,  102,  392,
      102,  398,  402,  393,  381,  102,  405,  401,  102,  396,
      387,   22,   22,   22,   22,   22,   24,   24,   24,   24,

       24,   36,   36,   36,   36,   36,   37,   37,   37,   37,
       37,   44,   44,   44,   44,   44,   45,   45,   45,   45,
       45,   46,   46,   46,   46,   46,   47,   47,   47,   47,
       47,   50,   50,   50,   50,   50,   58,  395,   58,   62,
       62,  394,   62,   62,   65,   65,  391,   65,   65,   69,
       69,   69,   69,   69,   71,   71,   71,   71,   71,   73,
       73,  390,   73,   73,   78,   78,   78,   78,   78,   80,
       80,   80,   80,   80,   82,   82,   82,   82,   82,   85,
       85,   85,   85,   85,   87,   87,   87,   87,   87,   89,
       89,   89,   89,   89,   99,   99,  389,   99,   99,  108,

      384,  108,  108,  108,  126,  126,  378,  126,  126,  127,
      127,  372,  127,  127,  128,  128,  366,  128,  128,  131,
      131,  360,  131,  131,  139,  139,  139,  139,  146,  146,
      354,  146,  146,  147,  147,  349,  147,  147,  152,  152,
      152,  152,  152,  183,  183,  183,  183,  183,  192,  192,
      348,  192,  192,  218,  218,  218,  218,  218,  228,  228,
      228,  228,  228,  237,  237,  346,  237,  237,  287,  287,
      287,  287,  287,  290,  290,  290,  290,  290,  292,  292,
      292,  292,  292,  300,  300,  300,  300,  300,  304,  304,
      304,  304,  304,  313,  313,  313,  313,  330,  330,  330,

      330,  330,  331,  331,  342,  331,  331,  338,  338,  338,
      338,  338,  339,  339,  341,  339,  339,  397,  397,  397,
      397,  397,  399,  399,  102,  399,  399,  400,  400,  336,
      400,  400,  406,  406,  406,  406,  406,  333,  102,  328,
      316,  325,  323,  319,  305,  316,  314,  312,  306,  305,
      299,  298,  102,  288,   48,  278,  268,  258,  249,  247,
      241,  235,  231,  224,  222,  213,  211,  204,  203,  201,
      194,  193,  190,  102,  182,  181,  179,  171,  170,  168,
      166,  161,  160,  157,  156,  154,   48,  148,  145,  144,
      143,  140,  137,  130,  129,  123,  122,  121,  119,   90,

       88,   86,  113,  112,   83,  111,   81,  110,   79,   83,
       81,   79,  109,   72,   70,  107,  106,  105,  102,  101,
      100,   97,   48,   90,   88,   86,   84,   83,   81,   79,
       72,   70,   68,   67,   48,  408,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   21,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408

    } ;

static const flex_int16_t yy_chk[892] =
    {   0,
        0,    4,    4,   11,    4,   12,   25,   28,   25,   63,
       28,    4,   11,   29,   12,   27,   27,   27,   31,   32,
       31,   32,   49,   49,   54,   28,   33,   33,   33,   33,
       53,    4,    6,    6,    6,    6,   52,    6,    6,    6,
        6,   63,   39,   29,   39,   50,   50,   51,   51,   53,
       56,  406,   56,   54,   52,   39,   39,   57,   64,   57,
       91,   39,    6,    6,   14,   14,   14,   58,   58,   58,
       58,   94,   64,   95,   98,   93,   93,   14,   14,   51,
       66,   96,   96,   14,   66,   66,   66,   66,   98,  103,
       94,   95,   91,  104,   14,   30,  114,   30,   30,   93,

       30,   30,   30,   30,   74,   30,   74,   30,  116,  104,
      115,  115,  117,  103,  118,  120,  124,   74,   74,  125,
      114,  132,  117,   74,  133,  133,  116,  138,   30,  134,
      136,  120,  141,  149,  125,  115,  151,  118,  159,  134,
      153,  124,  138,  142,  142,  151,  132,  150,  150,  155,
      155,  133,  158,  162,  136,  163,  163,  167,  159,  141,
      149,  165,  153,  169,  165,  173,  174,  159,  177,  175,
      159,  150,  176,  176,  178,  180,  158,  162,  184,  185,
      189,  186,  187,  169,  197,  188,  191,  167,  195,  196,
      196,  177,  169,  175,  173,  198,  174,  200,  184,  199,

      205,  202,  178,  186,  180,  187,  191,  208,  185,  188,
      206,  189,  207,  210,  197,  195,  212,  214,  215,  198,
      209,  199,  216,  217,  219,  220,  227,  200,  202,  208,
      206,  223,  209,  221,  225,  217,  205,  209,  229,  230,
      217,  207,  226,  232,  234,  233,  210,  215,  236,  239,
      214,  240,  212,  242,  219,  216,  243,  220,  225,  221,
      227,  244,  226,  245,  223,  238,  238,  250,  229,  233,
      246,  230,  236,  232,  248,  248,  239,  240,  234,  251,
      243,  253,  252,  242,  255,  256,  254,  262,  257,  259,
      260,  261,  264,  244,  245,  270,  246,  266,  250,  267,

      263,  265,  265,  273,  273,  269,  271,  255,  272,  274,
      260,  279,  256,  253,  405,  251,  252,  254,  257,  264,
      259,  266,  262,  263,  261,  269,  286,  270,  267,  275,
      271,  280,  272,  274,  276,  276,  275,  282,  282,  280,
      283,  284,  284,  279,  285,  290,  286,  283,  285,  289,
      289,  293,  294,  290,  295,  296,  294,  289,  297,  296,
      300,  302,  303,  303,  309,  307,  308,  311,  300,  302,
      308,  317,  314,  320,  295,  315,  315,  322,  324,  317,
      326,  329,  293,  334,  302,  307,  297,  314,  311,  329,
      332,  332,  309,  335,  337,  317,  326,  343,  322,  340,

      344,  345,  347,  329,  324,  320,  347,  340,  337,  334,
      351,  340,  352,  350,  353,  355,  356,  357,  335,  361,
      343,  350,  359,  359,  356,  344,  358,  362,  363,  364,
      364,  367,  369,  400,  351,  362,  345,  355,  353,  357,
      363,  361,  373,  350,  365,  368,  356,  352,  371,  365,
      358,  370,  371,  368,  375,  367,  370,  373,  381,  362,
      387,  376,  369,  374,  374,  376,  379,  377,  368,  380,
      382,  374,  377,  379,  398,  382,  399,  380,  386,  386,
      393,  393,  398,  387,  375,  402,  402,  397,  392,  391,
      381,  409,  409,  409,  409,  409,  410,  410,  410,  410,

      410,  411,  411,  411,  411,  411,  412,  412,  412,  412,
      412,  413,  413,  413,  413,  413,  414,  414,  414,  414,
      414,  415,  415,  415,  415,  415,  416,  416,  416,  416,
      416,  417,  417,  417,  417,  417,  418,  390,  418,  419,
      419,  388,  419,  419,  420,  420,  385,  420,  420,  421,
      421,  421,  421,  421,  422,  422,  422,  422,  422,  423,
      423,  384,  423,  423,  424,  424,  424,  424,  424,  425,
      425,  425,  425,  425,  426,  426,  426,  426,  426,  427,
      427,  427,  427,  427,  428,  428,  428,  428,  428,  429,
      429,  429,  429,  429,  430,  430,  383,  430,  430,  431,

      378,  431,  431,  431,  432,  432,  372,  432,  432,  433,
      433,  366,  433,  433,  434,  434,  360,  434,  434,  435,
      435,  354,  435,  435,  436,  436,  436,  436,  437,  437,
      346,  437,  437,  438,  438,  339,  438,  438,  439,  439,
      439,  439,  439,  440,  440,  440,  440,  440,  441,  441,
      338,  441,  441,  442,  442,  442,  442,  442,  443,  443,
      443,  443,  443,  444,  444,  336,  444,  444,  445,  445,
      445,  445,  445,  446,  446,  446,  446,  446,  447,  447,
      447,  447,  447,  448,  448,  448,  448,  448,  449,  449,
      449,  449,  449,  450,  450,  450,  450,  451,  451,  451,

      451,  451,  452,  452,  331,  452,  452,  453,  453,  453,
      453,  453,  454,  454,  330,  454,  454,  455,  455,  455,
      455,  455,  456,  456,  327,  456,  456,  457,  457,  325,
      457,  457,  458,  458,  458,  458,  458,  321,  318,  316,
      313,  312,  310,  305,  304,  301,  299,  298,  292,  291,
      288,  287,  281,  278,  277,  268,  258,  247,  237,  235,
      228,  222,  218,  213,  211,  204,  201,  193,  192,  190,
      183,  182,  179,  172,  171,  170,  168,  157,  156,  154,
      152,  147,  146,  140,  139,  137,  135,  131,  128,  127,
      126,  123,  119,  112,  111,  101,  100,   99,   97,   89,

       87,   85,   84,   83,   82,   81,   80,   79,   78,   77,
       76,   75,   73,   71,   69,   68,   67,   65,   62,   61,
       60,   55,   47,   46,   45,   44,   43,   42,   41,   40,
       37,   36,   35,   34,   24,   21,   20,   19,   18,   17,
       16,   15,   13,   10,    9,    8,    7,    5,    3,    2,
        1,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408

    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ChargDesamb.fl"
/*	$Log: ChargDesamb.fl,v $
/*	Revision 1.1.1.1  2006/05/03 11:35:11  ht
/*	SynoTerm - Environnement d'acquisition de relations sémantiques entre termes
/*	
 *	Revision 1.3  2001/05/01 19:13:13  thierry
 *	Correction des commentaires de log
 *
 *	Revision 1.2  2001/05/01 19:06:04  thierry
 *	*** empty log message ***
 */	
#line 12 "ChargDesamb.fl"
	/*
        Creer a partir de des2gnm.l (Adeline Nazarenko Juillet 96)
	
	permet de charger le fichier .desamb issu de l'analyse d'un
	corpus par LEXTER
	
	Le prefixe des variables Flex est "ChDes"
	
	A Voir : Separer les differents champs <CatG> Lemme [Forme Flechie]
	*/

#include<stdio.h>
#include<stdlib.h>
#include<malloc.h>
#include "VarSem.h"

/* Nombre de champs */

#define NB_CHP_DESAMB	6
#define NB_MAX_SUBTREE 20
#define MAX_COMP 3000
#define IDPHRLGTH 100

FILE *Filedb,*FiledbTeteS,*FiledbExpS, *FiledbPhr;
/*FILE *FiledbTeteC,*FiledbExpC, *FiledbGNMax;*/

int compteur=0,compteurCTMAX=0,i;
char *textunitid,*seqid;

char *GNPrec[NB_MAX_SUBTREE];
char *GN=NULL;
int IdGNPrec[NB_MAX_SUBTREE];
char IdPhr[IDPHRLGTH]="";
char Tete[MAX_COMP],Exp[MAX_COMP],Coord[200];
char Categ[MAX_COMP],Lemme[MAX_COMP], Graphie[MAX_COMP];
char Phrase[10000], *tmp;
int IdTete,IdExp;
char Compprec[NB_MAX_SUBTREE][3000];
int nb_subtree=0, nb_stree_n_u=0;
/****************/

#line 1123 "lex.ChDes.c"

#line 1125 "lex.ChDes.c"

#define INITIAL 0
#define normal 1
#define GNManalyse 2
#define non 3
#define GNM 4
#define sousGNManalyse 5
#define GNManalyseComp 6
#define GNManalyseCompT 7
#define GNManalyseCompC 8
#define GNManalyseCompE 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 56 "ChargDesamb.fl"

#line 58 "ChargDesamb.fl"
	BEGIN normal ;

#line 1365 "lex.ChDes.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 409 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 852 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 60 "ChargDesamb.fl"
{
	/* On laisse tomber les gnm 101
	 * (TH) Raison : ???
	 * (TH) Donc choix a reconsiderer peut-etre ?
	 */ ;
							}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 66 "ChargDesamb.fl"
{
	/* On laisse tomber les regles 900
	 * N et N 
	 * (TH) Raison : beaucoup trop d'erreurs
	 */ ;
							}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 72 "ChargDesamb.fl"
{
	/* Pour eviter de rentrer dans l'etat
	 * GNM analyse quand on lit un "non"
	 * alors qu'on est dans l'etat normal
	 * (TH) A mon avis, ca ne doit pas servir
	 *  souvent !
	 */
	;
								}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 81 "ChargDesamb.fl"
{
	/* On commence a lire la decomposition 
	 * d'un GNM
	 */
	/*printf("+\n") ;*/
	BEGIN GNManalyse ;
					}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 88 "ChargDesamb.fl"
{
	/* On commence a lire la decomposition 
	 * d'un GNM
	 */
	/*printf("+\n") ;*/
	BEGIN GNManalyse ;
					}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 95 "ChargDesamb.fl"
{
	/* On commence a lire la decomposition 
	 * d'un GNM dans un enchassement decCoord
	 */
	BEGIN GNManalyse ;
					}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 101 "ChargDesamb.fl"
{
	 strcpy(IdPhr,ChDestext);
	 IdPhr[ChDesleng-1]=0;
			}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 105 "ChargDesamb.fl"
{
	if (ChDestext[5] == '\"') {
	    tmp = ChDestext + 6;
	    strcpy(Phrase,tmp);
	    Phrase[strlen(Phrase) - 2] = 0;
	} else {
	    tmp = ChDestext + 5;
	    strcpy(Phrase,tmp);
	    Phrase[strlen(Phrase) - 1] = 0;
	}
	fprintf(FiledbPhr,"%s|%s\n",IdPhr,Phrase);
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 119 "ChargDesamb.fl"
{
	/*(TH) On degage tout ce qui ne semble pas utile
	 *
	 */
	;
			}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 126 "ChargDesamb.fl"
{
	/* Le GNM a ete
	 * analyse par decCoord 
	 */
	BEGIN GNM ;
								}
	YY_BREAK
case 11:
/* rule 11 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 33);
(yy_c_buf_p) = yy_cp = yy_bp + 33;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 132 "ChargDesamb.fl"
{
	/* Le GNM a ete
	 * analyse par decCoord 
	 */
	BEGIN GNM ;
								}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 138 "ChargDesamb.fl"
{
	/* Le GNM a ete
	 * analyse mais c'est
	 * un GNM enchâssé
	 * dans un autre
	 *//*writelogS("Etat tGNM analyse par");*/
	;
							}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 146 "ChargDesamb.fl"
{
	/* Le GNM a ete analyse
	 *//*writelogS("Etat GNM analyse par");*/
	BEGIN GNM ;
							}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 151 "ChargDesamb.fl"
{
	/* Le GNM n'a pas ete analyse
	 */
	/* (TH) On oublie l'analyse 
	 *      Voir ce que je dois faire ici
	 *      => A priori rien de special (02/05/98)
	 */
	BEGIN normal ;
						}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 160 "ChargDesamb.fl"
{
	/* On lit le GNM
	 * (TH) A enlever
	 */
	/*writelogI(compteur);*/
	i = 0;
	while((i<NB_MAX_SUBTREE)&&(GNPrec[i]==NULL)&&(IdGNPrec[i]==-1)) i++;
	
	strcpy(Tete,ChDestext);
	Tete[ChDesleng-1]=0;
	if ((i<NB_MAX_SUBTREE)&&(GNPrec[i]!=NULL)&&(IdGNPrec[i]!=-1)){
	    /*writelogS(Compprec[i]);*/
	    fprintf(Filedb,"%d:%s:%s\n",compteurCTMAX,Compprec[i],IdPhr);
	    fprintf(FiledbTeteS,"%s\n",Compprec[i]);
	    /*fprintf(FiledbGNMax,"%s:%s:%s\n",Compprec[i],Tete,IdPhr);*/
	    compteurCTMAX++;
	    GNPrec[i]=GN;
	}
	else {
	    fprintf(stderr,"GNMProbleme aucun GNPrec plein\n");
	    writelogS("GNMProbleme aucun GNPrec plein");
	    writelogS(GN);
	}
	
	for(i=0;i<NB_MAX_SUBTREE;i++){
	    GNPrec[i] = NULL;
	    IdGNPrec[i] = -1;
	}
	nb_stree_n_u=0;
	BEGIN normal ;
			}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 192 "ChargDesamb.fl"
;
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 193 "ChargDesamb.fl"
;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 194 "ChargDesamb.fl"
;
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 195 "ChargDesamb.fl"
;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 196 "ChargDesamb.fl"
;
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 198 "ChargDesamb.fl"
{BEGIN sousGNManalyse;
				/* Modifier pour LEXTER99 
				<GNManalyse>^\t+/"<"[^\n]+\n
				*/
					 /*writelogS("Etat GNManalyse <");*/
				}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 204 "ChargDesamb.fl"
{BEGIN sousGNManalyse;
					 /*writelogS("Etat GNManalyse <");*/
				}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 208 "ChargDesamb.fl"
{ BEGIN non ;
				}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 210 "ChargDesamb.fl"
{
	/* lecture d'un sous-groupe du GNM */
	 /*writelogS("Etat sous GNManalyse <");*/
	GN=(char *)malloc(sizeof(char)*(ChDesleng+1));
	strcpy(GN, ChDestext) ;
	GN[ChDesleng-1]=0 ;
	/* Et on commence l'analyse des composants */
	BEGIN GNManalyseComp ;
					}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 219 "ChargDesamb.fl"
{ 
	/*
	 * Analyse de la Tete 
	 */
	BEGIN GNManalyseCompT ;
						}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 225 "ChargDesamb.fl"
{ 
	/*
	 * Analyse de la Tete 
	 */
	strcpy(Tete,ChDestext);
	Tete[ChDesleng-1]=0;
	i = 0;
	while(i<NB_MAX_SUBTREE) {
	    if ((GNPrec[i]!=NULL)&&(strcmp(GNPrec[i],Tete)==0)&&(IdGNPrec[i]!=-1))
		break;
	    i++;
	}
	if ((i<NB_MAX_SUBTREE)&&(GNPrec[i]!=NULL)&&(strcmp(GNPrec[i],Tete)==0)){
	    /* La tete est le GNPrec i (deja analyse) */
	    /*fprintf(FiledbTeteC,"%s:%s:",Compprec[i],Tete);*/
	    strcpy(Tete,Compprec[i]);
	    IdTete=IdGNPrec[i];
	    free(GNPrec[i]);
	    GNPrec[i]=NULL;
	    IdGNPrec[i]=-1;
	    if (i < nb_stree_n_u) {
		nb_stree_n_u = i;
	    }
	}
	else {
	    /*Decoup_Forme(Categ, Lemme, Graphie, Tete);*/
	    
	    /*writelogS(Tete);*/
	    IdTete=compteur;
	}
	fprintf(FiledbTeteS,"%s\n",Tete);
	compteur++;
	BEGIN GNManalyseComp ;
	}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 260 "ChargDesamb.fl"
{ 
	/*
	 * Analyse de la Coordination 
	 */
	BEGIN GNManalyseCompC ;
						}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 267 "ChargDesamb.fl"
{
	strcpy(Coord,ChDestext);
	Coord[ChDesleng-1]=0;
	BEGIN GNManalyseComp ;
				}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 273 "ChargDesamb.fl"
{ 
	/*
	 * Analyse de l'Expansion 
	 */
	BEGIN GNManalyseCompE ;
						}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 280 "ChargDesamb.fl"
{ 
	/*
	 * Insertion de l'expansion 
	 */
	strcpy(Exp,ChDestext);
	Exp[ChDesleng-1]=0;
	i = 0;
	while(i<NB_MAX_SUBTREE) {
	    if ((GNPrec[i]!=NULL)&&(strcmp(GNPrec[i],Exp)==0) && (IdGNPrec[i]!=-1))
		break;
	    i++;
	}
	if ((i<NB_MAX_SUBTREE)&&(GNPrec[i]!=NULL)&&(strcmp(GNPrec[i],Exp)==0)){
	    /* L'expansion est le GNPrec i (deja analyse) */
	    /*fprintf(FiledbExpC,"%s:%s\n",Compprec[i],Exp);*/
	    strcpy(Exp,Compprec[i]);
	    IdExp=IdGNPrec[i];
	    free(GNPrec[i]);
	    GNPrec[i]=NULL;
	    IdGNPrec[i]=-1;
	    if (i < nb_stree_n_u) {
		nb_stree_n_u = i;
	    }
	}
	else {
	    /* L'expansion est un mot simple */
	    /*Decoup_Forme(Categ, Lemme, Graphie, Exp);*/
	    /*writelogI(i);*/
	    
	    /*writelogS(Exp);*/
	    IdExp=compteur;
	}
	fprintf(FiledbExpS,"%s\n",Exp);
	/* On construit une partie du GN : 
	 * la tete + la coord + l'exp
	 */
	/*compteur++;*/
	sprintf(Compprec[nb_stree_n_u],"{%s|%s|%s}",Tete,Coord,Exp);
	GNPrec[nb_stree_n_u]=GN;
	IdGNPrec[nb_stree_n_u]=compteur;
	i = nb_stree_n_u;
	while((i<NB_MAX_SUBTREE)&&(GNPrec[i]!=NULL)&&(IdGNPrec[i]!=-1)) i++;
	if (i>=NB_MAX_SUBTREE) {
	    fprintf(stderr,"GNManalyseProbleme aucun GNPrec libre\n");
	    writelogS("GNManalyseProbleme aucun GNPrec libre");
	    writelogS(GN);
	}
	else {
	    nb_stree_n_u = i;
	}
	compteur++;
	BEGIN GNManalyse ;
				}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 334 "ChargDesamb.fl"
{ /*writelogS("Etat nonnon");*/
				BEGIN non ;
			}
	YY_BREAK
case 32:
/* rule 32 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 337 "ChargDesamb.fl"
{ /*writelogS("Etat nont");*/
				BEGIN GNManalyse ;
			}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 340 "ChargDesamb.fl"
{ /*writelogS("Etat non");*/
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 343 "ChargDesamb.fl"
{/*fprintf(stderr,"%s",ChDestext);*/}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 344 "ChargDesamb.fl"
ECHO;
	YY_BREAK
#line 1900 "lex.ChDes.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(normal):
			case YY_STATE_EOF(GNManalyse):
			case YY_STATE_EOF(non):
			case YY_STATE_EOF(GNM):
			case YY_STATE_EOF(sousGNManalyse):
			case YY_STATE_EOF(GNManalyseComp):
			case YY_STATE_EOF(GNManalyseCompT):
			case YY_STATE_EOF(GNManalyseCompC):
			case YY_STATE_EOF(GNManalyseCompE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 409 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 409 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 408);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 344 "ChargDesamb.fl"

int ChDeswrap()
{
    return(1);
}

int Charge_desamb(char *nom_desamb,char *nom_db, int typo, int iso)
{
    FILE *FichDesamb,*FileEnt;
    char *nom_desambdbent, nom_desambdbphr[100];
    char nom_desambdbtetes[100] ,nom_desambdbexps[100];
    char cmd[3000];
    int i;
    
	/* Chargement en Memoire */

    if ((Filedb = fopen(nom_db,"w"))==NULL){
      fprintf(stderr,"Ouverture de la table %s impossible\n", nom_db);
      fprintf(stderr,"fichier %s, ligne %d\n",__FILE__, __LINE__ - 2);
      return(ERR_TRAITMT);     
    }
    strcpy(nom_desambdbtetes,nom_db);
    strcat(nom_desambdbtetes,".tetes");
    if ((FiledbTeteS = fopen(nom_desambdbtetes,"w"))==NULL){
      fprintf(stderr,"Ouverture de la table %s impossible\n", nom_desambdbtetes);
      fprintf(stderr,"fichier %s, ligne %d\n",__FILE__, __LINE__ - 2);
      return(ERR_TRAITMT);     
    }
    strcpy(nom_desambdbexps,nom_db);
    strcat(nom_desambdbexps,".exps");
    if ((FiledbExpS = fopen(nom_desambdbexps,"w"))==NULL){
      fprintf(stderr,"Ouverture de la table %s impossible\n", nom_desambdbexps);
      fprintf(stderr,"fichier %s, ligne %d\n",__FILE__, __LINE__ - 2);
      return(ERR_TRAITMT);     
    }

    strcpy(nom_desambdbphr,nom_db);
    strcat(nom_desambdbphr,".phr");
    if ((FiledbPhr = fopen(nom_desambdbphr,"w"))==NULL){
      fprintf(stderr,"Ouverture de la table %s impossible\n", nom_desambdbphr);
      fprintf(stderr,"fichier %s, ligne %d\n",__FILE__, __LINE__ - 2);
      return(ERR_TRAITMT);     
    }

    if (iso) {
	sprintf(cmd,"ISO8859toSGML.pl %s",nom_desamb);
	system(cmd);
    }
    sprintf(cmd,"cp -f %s %s.old;sed -e \"s/XXNom/NomXX/\" %s.old > %s;rm -f %s.old",nom_desamb, nom_desamb, nom_desamb, nom_desamb, nom_desamb);
    system(cmd);
    if ((FichDesamb = fopen(nom_desamb,"r"))==NULL){
      fprintf(stderr,"Ouverture du fichier %s impossible\n", nom_desamb);
      fprintf(stderr,"fichier %s, ligne %d\n",__FILE__, __LINE__ - 2);
      return(ERR_TRAITMT);     
    }
    ChDesin = FichDesamb;
    writelogS("Appel de la fonction ChDeslex");
    /* Initialisation */
    for(i=0;i<NB_MAX_SUBTREE;i++){
	GNPrec[i] = NULL;
	IdGNPrec[i] = -1;
    }
    nb_stree_n_u =0;
    compteurCTMAX=0;
    /******************/
    ChDeslex();
    fclose(FichDesamb);
    fclose(Filedb);
    fclose(FiledbTeteS);
    fclose(FiledbExpS);
    fclose(FiledbPhr);

    /* Creation du fichier d'entete */
  
    if ((nom_desambdbent = (char *)malloc(sizeof(char)*(strlen(nom_desamb)+5)))==NULL){
      fprintf(stderr,"Erreur d'allocation memoire\n");
      fprintf(stderr,"fichier %s, ligne %d\n",__FILE__, __LINE__ - 2);
      return(ERR_ALLOCATION);
    }
    strcpy(nom_desambdbent,nom_db);
    strcat(nom_desambdbent,".ent");
  
    if ((FileEnt = fopen(nom_desambdbent,"w"))==NULL){
      fprintf(stderr,"Ouverture du fichier d'entete %s impossible\n", nom_desambdbent);
      fprintf(stderr,"fichier %s, ligne %d\n",__FILE__, __LINE__ - 2);
      return(ERR_TRAITMT);     
    }
    fprintf(FileEnt,"Type = corpus\n"); 
    fprintf(FileEnt,"Typographie = %d\n",typo); 
    fprintf(FileEnt,"Champs = IDCTMAX;<Tete|Coord|Exp>;IdPhrase\n"); 
    fprintf(FileEnt,"Nombre de GNM = %d\n",compteurCTMAX); 
    fprintf(FileEnt,"Nombre de Candidats Termes = %d\n",compteur); 

    fclose(FileEnt);

    strcpy(cmd,"ChargDesamb.pl ");
    strcat(cmd,nom_db);
    system(cmd);

    return(EXEC_OK);
}

Decoup_Forme(char *Cat,char *Lem,char *FF,char *nom)
{
   int i,l,j;
      
   i = 1;
   l = strlen(nom);
   j=0;
   while ((i<l)&&(nom[i]!='>')){
     Cat[j]=nom[i];
     i++;
     j++;
   }
   i++;
   Cat[j] = 0;
   
   /* On elimine les blancs au debut */
   while((i<l)&&(nom[i]==' ')) i++;
   
   j = 0;
   while((i<l)&&(nom[i]!='[')){
     Lem[j] = nom[i];
     i++;
     j++;
   }
   i++;
   Lem[j] = 0;
   /* On elimine les blancs a la fin */
   j = strlen(Lem)-1;
   while((j>0)&&(Lem[j]==' ')){
     Lem[j] = 0;
     j--;
   }
   j=0;
   while((j<l)&&(nom[i]!=']')){
     FF[j] = nom[i];
     i++;
     j++;
   }
   FF[j]=0;
   /* On elimine les blancs a la fin */
   j = strlen(FF)-1;
   while((j>0)&&(FF[j]==' ')){
     FF[j] = 0;
     j--;
   }
}


